package com.newsweaver.demo.colorservice.model;

import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class ColorSet {

    private static final List<Color> colors = Arrays.asList(
            new Color("aliceblue", "F0F8FF"),
            new Color("antiquewhite", "FAEBD7"),
            new Color("aquamarine", "7FFFD4"),
            new Color("azure", "F0FFFF"),
            new Color("beige", "F5F5DC"),
            new Color("bisque", "FFE4C4"),
            new Color("black", "000000"),
            new Color("blanchedalmond", "FFEBCD"),
            new Color("blue", "0000FF"),
            new Color("blueviolet", "8A2BE2"),
            new Color("brown", "A52A2A"),
            new Color("burlywood", "DEB887"),
            new Color("cadetblue", "5F9EA0"),
            new Color("chartreuse", "7FFF00"),
            new Color("chocolate", "D2691E"),
            new Color("coral", "FF7F50"),
            new Color("cornflowerblue", "6495ED"),
            new Color("cornsilk", "FFF8DC"),
            new Color("cyan", "00FFFF"),
            new Color("darkgoldenrod", "B8860B"),
            new Color("darkgreen", "006400"),
            new Color("darkkhaki", "BDB76B"),
            new Color("darkolivegreen", "556B2F"),
            new Color("darkorange", "FF8C00"),
            new Color("darkorchid", "9932CC"),
            new Color("darksalmon", "E9967A"),
            new Color("darkseagreen", "8FBC8F"),
            new Color("darkslateblue", "483D8B"),
            new Color("darkslategray", "2F4F4F"),
            new Color("darkturquoise", "00CED1"),
            new Color("darkviolet", "9400D3"),
            new Color("deeppink", "FF1493"),
            new Color("deepskyblue", "00BFFF"),
            new Color("dimgray", "696969"),
            new Color("dodgerblue", "1E90FF"),
            new Color("firebrick", "B22222"),
            new Color("floralwhite", "FFFAF0"),
            new Color("forestgreen", "228B22"),
            new Color("gainsboro", "DCDCDC"),
            new Color("ghostwhite", "F8F8FF"),
            new Color("gold", "FFD700"),
            new Color("goldenrod", "DAA520"),
            new Color("gray", "808080"),
            new Color("green", "008000"),
            new Color("greenyellow", "ADFF2F"),
            new Color("honeydew", "F0FFF0"),
            new Color("hotpink", "FF69B4"),
            new Color("indianred", "CD5C5C"),
            new Color("ivory", "FFFFF0"),
            new Color("khaki", "F0E68C"),
            new Color("lavender", "E6E6FA"),
            new Color("lavenderblush", "FFF0F5"),
            new Color("lawngreen", "7CFC00"),
            new Color("lemonchiffon", "FFFACD"),
            new Color("lightblue", "ADD8E6"),
            new Color("lightcoral", "F08080"),
            new Color("lightcyan", "E0FFFF"),
            new Color("lightgoldenrod", "EEDD82"),
            new Color("lightgoldenrodyellow", "FAFAD2"),
            new Color("lightgray", "D3D3D3"),
            new Color("lightpink", "FFB6C1"),
            new Color("lightsalmon", "FFA07A"),
            new Color("lightseagreen", "20B2AA"),
            new Color("lightskyblue", "87CEFA"),
            new Color("lightslate", "8470FF"),
            new Color("lightslategray", "778899"),
            new Color("lightsteelblue", "B0C4DE"),
            new Color("lightyellow", "FFFFE0"),
            new Color("limegreen", "32CD32"),
            new Color("linen", "FAF0E6"),
            new Color("magenta", "FF00FF"),
            new Color("maroon", "B03060"),
            new Color("mediumaquamarine", "66CDAA"),
            new Color("mediumblue", "0000CD"),
            new Color("mediumorchid", "BA55D3"),
            new Color("mediumpurple", "9370DB"),
            new Color("mediumseagreen", "3CB371"),
            new Color("mediumslateblue", "7B68EE"),
            new Color("mediumspringgreen", "00FA9A"),
            new Color("mediumturquoise", "48D1CC"),
            new Color("mediumviolet", "C71585"),
            new Color("midnightblue", "191970"),
            new Color("mintcream", "F5FFFA"),
            new Color("mistyrose", "FFE4E1"),
            new Color("moccasin", "FFE4B5"),
            new Color("navajowhite", "FFDEAD"),
            new Color("navy", "000080"),
            new Color("oldlace", "FDF5E6"),
            new Color("olivedrab", "6B8E23"),
            new Color("orange", "FFA500"),
            new Color("orangered", "FF4500"),
            new Color("orchid", "DA70D6"),
            new Color("palegoldenrod", "EEE8AA"),
            new Color("palegreen", "98FB98"),
            new Color("paleturquoise", "AFEEEE"),
            new Color("palevioletred", "DB7093"),
            new Color("papayawhip", "FFEFD5"),
            new Color("peachpuff", "FFDAB9"),
            new Color("peru", "CD853F"),
            new Color("pink", "FFC0CB"),
            new Color("plum", "DDA0DD"),
            new Color("powderblue", "B0E0E6"),
            new Color("purple", "A020F0"),
            new Color("red", "FF0000"),
            new Color("rosybrown", "BC8F8F"),
            new Color("royalblue", "4169E1"),
            new Color("saddlebrown", "8B4513"),
            new Color("salmon", "FA8072"),
            new Color("sandybrown", "F4A460"),
            new Color("seagreen", "2E8B57"),
            new Color("seashell", "FFF5EE"),
            new Color("sienna", "A0522D"),
            new Color("skyblue", "87CEEB"),
            new Color("slateblue", "6A5ACD"),
            new Color("slategray", "708090"),
            new Color("snow", "FFFAFA"),
            new Color("springgreen", "00FF7F"),
            new Color("steelblue", "4682B4"),
            new Color("tan", "D2B48C"),
            new Color("thistle", "D8BFD8"),
            new Color("tomato", "FF6347"),
            new Color("turquoise", "40E0D0"),
            new Color("violet", "EE82EE"),
            new Color("violetred", "D02090"),
            new Color("wheat", "F5DEB3"),
            new Color("white", "FFFFFF"),
            new Color("whitesmoke", "F5F5F5"),
            new Color("yellow", "FFFF00"),
            new Color("yellowgreen", "9ACD32")
    );

    public static Color randomColor() {
        Random rng = new Random();
        return colors.get(rng.nextInt(colors.size()));
    }

}
